languageCode:           "en"
title:                  "Bootstrap RTL" #rtl
baseURL:                "https://bootstrapper.ir" #rtl
enableInlineShortcodes: true

markup:
  goldmark:
    renderer:
      unsafe:           true
  highlight:
    noClasses:          false
  tableOfContents:
    startLevel:         2
    endLevel:           6

buildDrafts:            true
buildFuture:            true

enableRobotsTXT:        true
metaDataFormat:         "yaml"
disableKinds:           ["404", "taxonomy", "taxonomyTerm", "RSS"]

publishDir:             "_gh_pages"

module:
  mounts:
    - source:           dist
      target:           static/docs/4.6/dist
    - source:           site/assets
      target:           assets
    - source:           site/content
      target:           content
    - source:           site/data
      target:           data
    - source:           site/layouts
      target:           layouts
    - source:           site/static
      target:           static
    - source:           site/static/docs/4.6/assets/img/favicons/apple-touch-icon.png
      target:           static/apple-touch-icon.png
    - source:           site/static/docs/4.6/assets/img/favicons/favicon.ico
      target:           static/favicon.ico

params:
  description:          "The most popular HTML, CSS, and JS library in the world."
  authors:              "Mark Otto, Jacob Thornton, and Bootstrap contributors"
  social_image_path:    /docs/4.6/assets/brand/bootstrap-social.png
  social_logo_path:     /docs/4.6/assets/brand/bootstrap-social-logo.png

  current_version:      "4.6.0 RTL rev. 1" #rtl
  current_ruby_version: "4.6.0 RTL rev. 1" #rtl
  docs_version:         "4.6"
  github_org:           "https://github.com/twbs"
  repo:                 "https://github.com/PerseusTheGreat/bootstrap-4-rtl" #rtl
  twitter:              "getbootstrap"
  slack:                "https://bootstrap-slack.herokuapp.com/"
  opencollective:       "https://opencollective.com/bootstrap"
  blog:                 "https://blog.getbootstrap.com/"
  expo:                 "https://expo.getbootstrap.com/"
  themes:               "https://themes.getbootstrap.com/"
  icons:                "https://icons.getbootstrap.com/"

  download:
    source:             "https://github.com/PerseusTheGreat/bootstrap-4-rtl/" #rtl
    dist:               "https://bootstrapper.ir/archive/bootstrap-4.6.0-plus-rtl-rev.1-dist.zip" #rtl
    dist_examples:      "https://bootstrapper.ir/archive/bootstrap-4.6.0-plus-rtl-rev.1-examples.zip" #rtl

  cdn:
    # See https://www.srihash.org for info on how to generate the hashes
    css:              "https://unpkg.com/@laylazi/bootstrap-rtl@4.6.0-1/dist/css/bootstrap-rtl.min.css" #rtl
    css_hash:         "sha384-6hU5Bu3enk7WzwAhFyBbTGcwPktzVxcjKBUetTESkYuVV+eDTLCDTttgjfIfiChW"
    js:               "https://unpkg.com/@laylazi/bootstrap-rtl@4.6.0-1/dist/js/bootstrap.min.js" #rtl
    js_hash:          "sha384-Ic6xVqzcKESTk7wpoYMynEJbHdqdyvVrUgrXr4eWHhZGlPWE4K2lMM6esL35iIR5"
    js_bundle:        "https://unpkg.com/@laylazi/bootstrap-rtl@4.6.0-1/dist/js/bootstrap.bundle.min.js" #rtl
    js_bundle_hash:   "sha384-P9y0hN+A/whi6LQ0JcXPGK841/5gUZr6+IPlAMVmnrIKuP5UjTv/PAFPKmHHyXpF"
    jquery:           "https://code.jquery.com/jquery-3.5.1.slim.min.js"
    jquery_hash:      "sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
    popper:           "https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
    popper_hash:      "sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
